/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/alpha-colors.ts
 * Command: astryx theme build src/theme/alpha-colors.ts
 * Generated: 2026-08-02T17:28:50.497Z
 */

/// <reference path="./alpha-colors.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const alphaColorsTheme: DefinedTheme;
