/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/alpha-colors.ts
 * Command: astryx theme build src/theme/alpha-colors.ts
 * Generated: 2026-08-03T09:17:40.225Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}

declare module '@astryxdesign/core/Section' {
  interface SectionVariantMap {
    'brand': true;
  }
}
