/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/alpha-colors.ts
 * Command: astryx theme build src/theme/alpha-colors.ts
 * Generated: 2026-08-02T17:28:50.495Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
